# Generated by Django 4.1.9 on 2023-05-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departments",
            fields=[
                ("DepartmentsId", models.AutoField(primary_key=True, serialize=False)),
                ("DepartmentsName", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                ("EmployeesId", models.AutoField(primary_key=True, serialize=False)),
                ("EmployeeName", models.CharField(max_length=100)),
                ("Department", models.CharField(max_length=100)),
                ("DataJoining", models.DateField()),
                ("PhotoFileName", models.CharField(max_length=100)),
            ],
        ),
    ]
